name: CICD
on: 
  workflow_dispatch: 
    inputs:
      environment:
        description: Environment
        required: true
        default: Stagging
        type: choice
        options:
          - Dev
          - Stagging
          - Deploy

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        run: echo "Code Fetched"
  build:
    runs-on: ubuntu-latest
    if: ${{inputs.environment == 'Dev'}}
    needs:
      - code
    steps:
      - name: Build App
        run: echo "App built successfully."
  test:
    runs-on: ubuntu-latest
    if: ${{inputs.environment == 'Stagging'}}
    needs:
      - build
    steps:
      - name: Test the Built App
        run: echo "Test Successfully"
  deploy:
    runs-on: ubuntu-latest
    if: ${{inputs.environment == 'Deploy'}}
    needs:
      - test
    steps:
      - name: Deploy App
        run: echo "App deploied successfully."
