name: Greet(Composite Action)
on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Greeting Composite Action
        id: get
        uses: ./.github/actions/setup-and-greet
        with:
          name: Harshit
          language: en
      - name: Verify
        run: |
          echo "Result: ${{steps.get.outputs.greet}}"
    
