name: Job Level Output
on: workflow_dispatch

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Set Date
        id: set_date
        run: |
          echo "date=$(date)" >> $GITHUB_OUTPUT
    outputs:
      set-date: ${{ steps.set_date.outputs.date }}

  print-date:
    needs: 
      - date
    runs-on: ubuntu-latest
    steps:
      - name: Print Today's Date
        run: |
          echo "Today's date is: ${{ needs.date.outputs.set-date }}"
