name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  manual_trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Manual Trigger
        run: echo "The workflow ran successfully and it was triggered manually"