name: SCHEDULE TRIGGER
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  schedule_greet:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Schedule Workflow Triggered
        run: echo "The Schedule Workflow will Trigger and run every day at midnight UTC"