name: Secrets Value Workflow
on: workflow_dispatch

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret is set or not
        run: |
          if [ -n ${{ secrets.MY_SECRET_MESSAGE }} ]; then
          echo "Secret:true"
          else
          echo "Secret:false"
          fi
      - name: Print Secret
        run: echo "Secret is: ${{ secrets.MY_SECRET_MESSAGE }}"
