name: Run Tests
on: 
  push:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Workflow run: 
        run: echo "This test.yml run at: $(date)"
